# Generated by Django 3.0.8 on 2020-10-02 10:51

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ivent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('area', models.TextField()),
                ('address', models.TextField(blank=True, max_length=124)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('reg_start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reg_finish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ivent_start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ivent_finish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ivents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
