# Generated by Django 3.0.8 on 2020-10-02 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0009_add_subregion'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivent',
            name='area',
            field=models.ForeignKey(default=350, on_delete=django.db.models.deletion.CASCADE, to='cities_light.City'),
        ),
    ]
