# Generated by Django 3.0.8 on 2020-10-03 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('main', '0003_auto_20201003_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivent',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ivents', to='users.Profile'),
        ),
    ]
