# Generated by Django 3.0.8 on 2020-10-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201003_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivent',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
