# Generated by Django 3.0.8 on 2020-10-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201019_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('cost', models.IntegerField()),
            ],
            options={
                'db_table': 'test',
            },
        ),
    ]
