# Generated by Django 3.0.8 on 2020-10-19 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_test'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='test',
            new_name='test_new',
        ),
    ]
