# Generated by Django 3.0.8 on 2020-10-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201019_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nuke',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nuke',
            },
        ),
        migrations.DeleteModel(
            name='test_new',
        ),
    ]
