# Generated by Django 3.0.8 on 2020-10-19 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201019_1955'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nuke',
        ),
    ]
