# Generated by Django 3.0.8 on 2020-10-19 20:59

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_delete_nuke'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivent',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
